apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: init
          image: postgres:15.0
          command: ["bash", "-c"]
          args:
            - |
              #create archive directory
              mkdir -p /data/archive && chown -R 999:999 /data/archive
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: false
      containers:
        - name: postgres
          image: postgres:15.0
          args: ["-c", "config_file=/config/postgresql.conf"]
          ports:
            - containerPort: 5432
              name: database
          env:
            - name: PGDATA
              value: "/data/pgdata"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
                  optional: false
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
                  optional: false
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: false
            - name: data
              mountPath: /data
              readOnly: false
          resources:
            limits:
              memory: "256Mi"
              cpu: "400m"
            requests:
              memory: "256Mi"
              cpu: "400m"
      volumes:
        - name: config
          configMap:
            name: postgres-configmap
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 100Mi
