apiVersion: v1
kind: Service
metadata:
  name: portal-web-service
  labels:
    app: portal-web
spec:
  type: NodePort
  selector:
    app: portal-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000