apiVersion: v1
kind: Service
metadata:
  name: webhooks-server-service
  labels:
    app: webhooks-server
spec:
  type: NodePort
  selector:
    app: webhooks-server
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090