apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app: worker
spec:
  type: NodePort
  selector:
    app: worker
  ports:
    # This is exposed just to have a health check endpoint
    - protocol: TCP
      port: 3000
      targetPort: 3000