apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: chronical-web-sa
      containers:
      - name: worker
        image: 'us-east1-docker.pkg.dev/chronical-dev/chronical-artifacts-repository/chronical-worker:0.0.3'
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
          - name: GET_HOSTS_FROM
            value: dns
        envFrom:
          - secretRef:
              name: common-secrets
          - secretRef:
              name: worker-secrets
          - configMapRef:
              name: common-configmap
          - configMapRef:
              name: worker-configmap
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 3
        #   periodSeconds: 3