apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migrator
spec:
  template:
    spec:
      containers:
        - name: migrator
          image: 'chronical-migrator:0.0.1'
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DB_CONNECTION_STRING
                  name: common-secrets
      restartPolicy: Never
  backoffLimit: 5